// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("Grid2DTags")));
bytes32 constant Grid2DTagsTableId = _tableId;

struct Grid2DTagsData {
  uint32 tags;
  address[] taggers;
}

library Grid2DTags {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.UINT32;
    _schema[1] = SchemaType.ADDRESS_ARRAY;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.UINT32;
    _schema[1] = SchemaType.UINT32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "tags";
    _fieldNames[1] = "taggers";
    return ("Grid2DTags", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get tags */
  function getTags(uint32 x, uint32 y) internal view returns (uint32 tags) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Get tags (using the specified store) */
  function getTags(IStore _store, uint32 x, uint32 y) internal view returns (uint32 tags) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (uint32(Bytes.slice4(_blob, 0)));
  }

  /** Set tags */
  function setTags(uint32 x, uint32 y, uint32 tags) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((tags)));
  }

  /** Set tags (using the specified store) */
  function setTags(IStore _store, uint32 x, uint32 y, uint32 tags) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((tags)));
  }

  /** Get taggers */
  function getTaggers(uint32 x, uint32 y) internal view returns (address[] memory taggers) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_address());
  }

  /** Get taggers (using the specified store) */
  function getTaggers(IStore _store, uint32 x, uint32 y) internal view returns (address[] memory taggers) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_address());
  }

  /** Set taggers */
  function setTaggers(uint32 x, uint32 y, address[] memory taggers) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    StoreSwitch.setField(_tableId, _keyTuple, 1, EncodeArray.encode((taggers)));
  }

  /** Set taggers (using the specified store) */
  function setTaggers(IStore _store, uint32 x, uint32 y, address[] memory taggers) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    _store.setField(_tableId, _keyTuple, 1, EncodeArray.encode((taggers)));
  }

  /** Get the length of taggers */
  function lengthTaggers(uint32 x, uint32 y) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    uint256 _byteLength = StoreSwitch.getFieldLength(_tableId, _keyTuple, 1, getSchema());
    return _byteLength / 20;
  }

  /** Get the length of taggers (using the specified store) */
  function lengthTaggers(IStore _store, uint32 x, uint32 y) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    uint256 _byteLength = _store.getFieldLength(_tableId, _keyTuple, 1, getSchema());
    return _byteLength / 20;
  }

  /** Get an item of taggers (unchecked, returns invalid data if index overflows) */
  function getItemTaggers(uint32 x, uint32 y, uint256 _index) internal view returns (address) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    bytes memory _blob = StoreSwitch.getFieldSlice(_tableId, _keyTuple, 1, getSchema(), _index * 20, (_index + 1) * 20);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Get an item of taggers (using the specified store) (unchecked, returns invalid data if index overflows) */
  function getItemTaggers(IStore _store, uint32 x, uint32 y, uint256 _index) internal view returns (address) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    bytes memory _blob = _store.getFieldSlice(_tableId, _keyTuple, 1, getSchema(), _index * 20, (_index + 1) * 20);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Push an element to taggers */
  function pushTaggers(uint32 x, uint32 y, address _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    StoreSwitch.pushToField(_tableId, _keyTuple, 1, abi.encodePacked((_element)));
  }

  /** Push an element to taggers (using the specified store) */
  function pushTaggers(IStore _store, uint32 x, uint32 y, address _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    _store.pushToField(_tableId, _keyTuple, 1, abi.encodePacked((_element)));
  }

  /** Pop an element from taggers */
  function popTaggers(uint32 x, uint32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    StoreSwitch.popFromField(_tableId, _keyTuple, 1, 20);
  }

  /** Pop an element from taggers (using the specified store) */
  function popTaggers(IStore _store, uint32 x, uint32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    _store.popFromField(_tableId, _keyTuple, 1, 20);
  }

  /** Update an element of taggers at `_index` */
  function updateTaggers(uint32 x, uint32 y, uint256 _index, address _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    StoreSwitch.updateInField(_tableId, _keyTuple, 1, _index * 20, abi.encodePacked((_element)));
  }

  /** Update an element of taggers (using the specified store) at `_index` */
  function updateTaggers(IStore _store, uint32 x, uint32 y, uint256 _index, address _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    _store.updateInField(_tableId, _keyTuple, 1, _index * 20, abi.encodePacked((_element)));
  }

  /** Get the full data */
  function get(uint32 x, uint32 y) internal view returns (Grid2DTagsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, uint32 x, uint32 y) internal view returns (Grid2DTagsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(uint32 x, uint32 y, uint32 tags, address[] memory taggers) internal {
    bytes memory _data = encode(tags, taggers);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, uint32 x, uint32 y, uint32 tags, address[] memory taggers) internal {
    bytes memory _data = encode(tags, taggers);

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(uint32 x, uint32 y, Grid2DTagsData memory _table) internal {
    set(x, y, _table.tags, _table.taggers);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, uint32 x, uint32 y, Grid2DTagsData memory _table) internal {
    set(_store, x, y, _table.tags, _table.taggers);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal view returns (Grid2DTagsData memory _table) {
    // 4 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 4));

    _table.tags = (uint32(Bytes.slice4(_blob, 0)));

    // Store trims the blob if dynamic fields are all empty
    if (_blob.length > 4) {
      uint256 _start;
      // skip static data length + dynamic lengths word
      uint256 _end = 36;

      _start = _end;
      _end += _encodedLengths.atIndex(0);
      _table.taggers = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_address());
    }
  }

  /** Tightly pack full data using this table's schema */
  function encode(uint32 tags, address[] memory taggers) internal view returns (bytes memory) {
    uint40[] memory _counters = new uint40[](1);
    _counters[0] = uint40(taggers.length * 20);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return abi.encodePacked(tags, _encodedLengths.unwrap(), EncodeArray.encode((taggers)));
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(uint32 x, uint32 y) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));
  }

  /* Delete all data for given keys */
  function deleteRecord(uint32 x, uint32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, uint32 x, uint32 y) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256((x)));
    _keyTuple[1] = bytes32(uint256((y)));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
