/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Counter: (() => {
      const tableId = new TableId("", "Counter");
      return defineComponent(
        world,
        {
          counterValue: RecsType.Number,
          counterValueSquared: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    TestData: (() => {
      const tableId = new TableId("", "TestData");
      return defineComponent(
        world,
        {
          testUint32: RecsType.Number,
          testBytes32: RecsType.String,
          testString: RecsType.String,
          testUint32Array: RecsType.NumberArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    TestKeyedData: (() => {
      const tableId = new TableId("", "TestKeyedData");
      return defineComponent(
        world,
        {
          testUint32: RecsType.Number,
          testBytes32: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Grid2D: (() => {
      const tableId = new TableId("", "Grid2D");
      return defineComponent(
        world,
        {
          isOccupied: RecsType.Boolean,
          data: RecsType.String,
          author: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Grid2DTags: (() => {
      const tableId = new TableId("", "Grid2DTags");
      return defineComponent(
        world,
        {
          tags: RecsType.Number,
          taggers: RecsType.StringArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Grid2DTagger: (() => {
      const tableId = new TableId("", "Grid2DTagger");
      return defineComponent(
        world,
        {
          tagX: RecsType.NumberArray,
          tagY: RecsType.NumberArray,
          timestamp: RecsType.BigIntArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    GridConstants: (() => {
      const tableId = new TableId("", "GridConstants");
      return defineComponent(
        world,
        {
          width: RecsType.Number,
          height: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
