// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterData, CounterTableId } from "./tables/Counter.sol";
import { TestData, TestDataData, TestDataTableId } from "./tables/TestData.sol";
import { TestKeyedData, TestKeyedDataData, TestKeyedDataTableId } from "./tables/TestKeyedData.sol";
import { Grid2D, Grid2DData, Grid2DTableId } from "./tables/Grid2D.sol";
import { GridConstants, GridConstantsData, GridConstantsTableId } from "./tables/GridConstants.sol";
import { NamespaceOwner, NamespaceOwnerTableId } from "./tables/NamespaceOwner.sol";
import { OwnerNamespaces, OwnerNamespacesTableId } from "./tables/OwnerNamespaces.sol";
