// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGridConstantsSystem {
  function testing_GridConstantsSys_setLimits(uint32 width, uint32 height) external;
}
