// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Grid2DData } from "./../Tables.sol";

interface IGrid2DSystem {
  error Unauthorized();

  function setGridPointData(uint32 x, uint32 y, bool isOccupied, bytes memory data, address author) external;

  function setGridPointData(uint32 x, uint32 y, Grid2DData memory data) external;
}
