// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IIncrementSystem {
  function testing_IncrementSystem_increment() external returns (uint32);

  function testing_IncrementSystem_incrementSquared() external returns (uint32);
}
