// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITestDataSystem {
  function pushRecordToTestData() external returns (uint32);

  function setInitialArray(uint32[] memory _array) external;

  function randomStringWithSeed(uint32 _seed) external view returns (string memory);
}
