// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITestDataSystem {
  function testing_TestDataSystem_pushRecordToTestData() external returns (uint32);

  function testing_TestDataSystem_setInitialArray(uint32[] memory _array) external;

  function testing_TestDataSystem_randomStringWithSeed(uint32 _seed) external view returns (string memory);
}
