// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITestKeyedDataSystem {
  function Test1_TestKeyedDataSys_pushRecordToTestKeyedData(uint32 _id) external returns (uint32);
}
