// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IUICreatorSystem {
  error NamespaceAlreadyExists(bytes16 namespace);

  function testing_UICreatorSystem_createNewNamespace(string memory name) external returns (bytes16);

  function testing_UICreatorSystem_createNewTableInNamespace(
    string memory namespaceName,
    string memory tableName
  ) external returns (bytes32);

  function testing_UICreatorSystem_createNewFieldInTable(
    string memory namespaceName,
    string memory tableName,
    string memory fieldName,
    uint8 fieldIndex
  ) external;

  function testing_UICreatorSystem_pushValueToField(
    string memory namespaceName,
    string memory tableName,
    string memory fieldName,
    uint8 fieldIndex,
    bytes calldata inputData
  ) external;

  function testing_UICreatorSystem_stringToBytes16(string memory input) external pure returns (bytes16);

  function testing_UICreatorSystem_stringToBytes32(string memory source) external pure returns (bytes32 result);
}
